image: debian:bookworm

build:
  stage: build
  tags: [Linux]

  before_script:
    - apt-get update && apt-get -y install ca-certificates git python3
    - git clone https://oauth2:DeS1JJ9wEZzY98hUgTfp@gitlab.rz.htw-berlin.de/bauers/ce24-co-verify /tmp/verify
    # Report HEAD log entry
    - git -C /tmp/verify log -1
    # Install additional packages needed by the lint script
    - apt-get -y --no-install-recommends install $(python3 /tmp/verify/lint.py --list-packages)
    # Install additional custom packages. In order to install more packages that are needed fo
    # your compiling process just add the names of the packages at the end of the next line
    - apt-get -y --no-install-recommends install

  script:
    - python3 /tmp/verify/lint.py
